#!/bin/sh
set -eu

export ABBY_RUNTIME_WALLET_API_BASE_URL="${ABBY_RUNTIME_WALLET_API_BASE_URL:-${VITE_WALLET_API_BASE_URL:-same-origin}}"
export ABBY_RUNTIME_WALLET_ID="${ABBY_RUNTIME_WALLET_ID:-}"
export ABBY_RUNTIME_ACTOR_DID="${ABBY_RUNTIME_ACTOR_DID:-}"
export ABBY_RUNTIME_ISSUER_KEY_HEX="${ABBY_RUNTIME_ISSUER_KEY_HEX:-}"
export ABBY_RUNTIME_AUDIENCE_KEY_HEX="${ABBY_RUNTIME_AUDIENCE_KEY_HEX:-}"
export ABBY_RUNTIME_FILECOIN_UPLOAD_URL="${ABBY_RUNTIME_FILECOIN_UPLOAD_URL:-}"
export ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN="${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN:-}"
export ABBY_RUNTIME_WALRUS_PUBLISHER_URL="${ABBY_RUNTIME_WALRUS_PUBLISHER_URL:-${VITE_WALRUS_STORAGE_PUBLISHER_URL:-}}"
export ABBY_RUNTIME_WALRUS_AGGREGATOR_URL="${ABBY_RUNTIME_WALRUS_AGGREGATOR_URL:-${VITE_WALRUS_STORAGE_AGGREGATOR_URL:-}}"
export ABBY_RUNTIME_WALRUS_DELETE_URL="${ABBY_RUNTIME_WALRUS_DELETE_URL:-${VITE_WALRUS_STORAGE_DELETE_URL:-}}"
export ABBY_RUNTIME_WALRUS_CLIENT_TOKEN="${ABBY_RUNTIME_WALRUS_CLIENT_TOKEN:-${VITE_WALRUS_STORAGE_CLIENT_TOKEN:-}}"
export ABBY_RUNTIME_WALRUS_EPOCHS="${ABBY_RUNTIME_WALRUS_EPOCHS:-${VITE_WALRUS_STORAGE_EPOCHS:-}}"
export ABBY_RUNTIME_WALRUS_DELETABLE="${ABBY_RUNTIME_WALRUS_DELETABLE:-${VITE_WALRUS_STORAGE_DELETABLE:-}}"
export ABBY_RUNTIME_VOICE_PROXY_ENABLED="${ABBY_RUNTIME_VOICE_PROXY_ENABLED:-${VITE_VOICE_PROXY_ENABLED:-}}"
export ABBY_RUNTIME_VOICE_PROXY_MODEL="${ABBY_RUNTIME_VOICE_PROXY_MODEL:-${VITE_VOICE_PROXY_MODEL:-}}"
export ABBY_RUNTIME_VOICE_PROXY_BASE_URL="${ABBY_RUNTIME_VOICE_PROXY_BASE_URL:-${IPFS_DATASETS_VOICE_PROXY_BASE_URL:-${VITE_VOICE_PROXY_BASE_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_INFER_URL="${ABBY_RUNTIME_VOICE_PROXY_INFER_URL:-${IPFS_DATASETS_VOICE_PROXY_INFER_URL:-${VITE_VOICE_PROXY_INFER_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_TTS_URL="${ABBY_RUNTIME_VOICE_PROXY_TTS_URL:-${IPFS_DATASETS_VOICE_PROXY_TTS_URL:-${VITE_VOICE_PROXY_TTS_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_STT_URL="${ABBY_RUNTIME_VOICE_PROXY_STT_URL:-${IPFS_DATASETS_VOICE_PROXY_STT_URL:-${VITE_VOICE_PROXY_STT_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL:-${IPFS_DATASETS_VOICE_PROXY_INFER_URL:-${VITE_VOICE_PROXY_FALLBACK_INFER_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL:-${IPFS_DATASETS_VOICE_PROXY_TTS_URL:-${VITE_VOICE_PROXY_FALLBACK_TTS_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL:-${IPFS_DATASETS_VOICE_PROXY_STT_URL:-${VITE_VOICE_PROXY_FALLBACK_STT_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL:-${VITE_VOICE_PROXY_FALLBACK_MODEL:-LiquidAI/LFM2.5-Audio-1.5B-proxy}}"
export ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD="${ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD:-${VITE_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD:-0.62}}"

# World ID / IDKit public UI runtime flags. Only IDKit-safe public values are
# injected into runtime-config.json. Backend secrets (RP signing key, HMAC key)
# are never exported here and must not appear in the rendered JSON.
export ABBY_RUNTIME_WORLD_ID_ENABLED="${ABBY_RUNTIME_WORLD_ID_ENABLED:-false}"
export ABBY_RUNTIME_WORLD_ID_APP_ID="${ABBY_RUNTIME_WORLD_ID_APP_ID:-}"
export ABBY_RUNTIME_WORLD_ID_ACTION="${ABBY_RUNTIME_WORLD_ID_ACTION:-wallet-attach-world-id-v1}"
export ABBY_RUNTIME_WORLD_ID_ENVIRONMENT="${ABBY_RUNTIME_WORLD_ID_ENVIRONMENT:-staging}"

envsubst \
  '${ABBY_RUNTIME_WALLET_API_BASE_URL} ${ABBY_RUNTIME_WALLET_ID} ${ABBY_RUNTIME_ACTOR_DID} ${ABBY_RUNTIME_ISSUER_KEY_HEX} ${ABBY_RUNTIME_AUDIENCE_KEY_HEX} ${ABBY_RUNTIME_FILECOIN_UPLOAD_URL} ${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN} ${ABBY_RUNTIME_VOICE_PROXY_ENABLED} ${ABBY_RUNTIME_VOICE_PROXY_MODEL} ${ABBY_RUNTIME_VOICE_PROXY_BASE_URL} ${ABBY_RUNTIME_VOICE_PROXY_INFER_URL} ${ABBY_RUNTIME_VOICE_PROXY_TTS_URL} ${ABBY_RUNTIME_VOICE_PROXY_STT_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL} ${ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD}' \
  < /opt/abby/runtime-config.template.json \
  > /usr/share/nginx/html/runtime-config.json
