#!/bin/sh
set -eu

export ABBY_RUNTIME_WALLET_API_BASE_URL="${ABBY_RUNTIME_WALLET_API_BASE_URL:-${VITE_WALLET_API_BASE_URL:-same-origin}}"
export ABBY_RUNTIME_WALLET_ID="${ABBY_RUNTIME_WALLET_ID:-}"
export ABBY_RUNTIME_ACTOR_DID="${ABBY_RUNTIME_ACTOR_DID:-}"
export ABBY_RUNTIME_ISSUER_KEY_HEX="${ABBY_RUNTIME_ISSUER_KEY_HEX:-}"
export ABBY_RUNTIME_AUDIENCE_KEY_HEX="${ABBY_RUNTIME_AUDIENCE_KEY_HEX:-}"
export ABBY_RUNTIME_FILECOIN_UPLOAD_URL="${ABBY_RUNTIME_FILECOIN_UPLOAD_URL:-}"
export ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN="${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN:-}"
export ABBY_RUNTIME_VOICE_PROXY_ENABLED="${ABBY_RUNTIME_VOICE_PROXY_ENABLED:-${VITE_VOICE_PROXY_ENABLED:-}}"
export ABBY_RUNTIME_VOICE_PROXY_MODEL="${ABBY_RUNTIME_VOICE_PROXY_MODEL:-${VITE_VOICE_PROXY_MODEL:-}}"
export ABBY_RUNTIME_VOICE_PROXY_BASE_URL="${ABBY_RUNTIME_VOICE_PROXY_BASE_URL:-${IPFS_DATASETS_VOICE_PROXY_BASE_URL:-${VITE_VOICE_PROXY_BASE_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_INFER_URL="${ABBY_RUNTIME_VOICE_PROXY_INFER_URL:-${IPFS_DATASETS_VOICE_PROXY_INFER_URL:-${VITE_VOICE_PROXY_INFER_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_TTS_URL="${ABBY_RUNTIME_VOICE_PROXY_TTS_URL:-${IPFS_DATASETS_VOICE_PROXY_TTS_URL:-${VITE_VOICE_PROXY_TTS_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_STT_URL="${ABBY_RUNTIME_VOICE_PROXY_STT_URL:-${IPFS_DATASETS_VOICE_PROXY_STT_URL:-${VITE_VOICE_PROXY_STT_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL:-${IPFS_DATASETS_VOICE_PROXY_INFER_URL:-${VITE_VOICE_PROXY_FALLBACK_INFER_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL:-${IPFS_DATASETS_VOICE_PROXY_TTS_URL:-${VITE_VOICE_PROXY_FALLBACK_TTS_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL:-${IPFS_DATASETS_VOICE_PROXY_STT_URL:-${VITE_VOICE_PROXY_FALLBACK_STT_URL:-}}}"
export ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL="${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL:-${VITE_VOICE_PROXY_FALLBACK_MODEL:-LiquidAI/LFM2.5-Audio-1.5B-proxy}}"
export ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL="${ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL:-}"
export ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD="${ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD:-${VITE_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD:-0.62}}"

if [ -n "$ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL" ]; then
  if printf '%s' "$ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL" \
    | LC_ALL=C grep -q '[\\"[:cntrl:]]'; then
    echo "ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL contains characters unsafe for runtime-config.json" >&2
    exit 1
  fi

  abby_manifest_without_scheme="${ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL#*://}"
  abby_manifest_authority="${abby_manifest_without_scheme%%/*}"
  abby_manifest_authority="${abby_manifest_authority##*@}"
  abby_manifest_host="${abby_manifest_authority%%:*}"
  abby_manifest_host="$(printf '%s' "$abby_manifest_host" | tr '[:upper:]' '[:lower:]')"
  abby_manifest_path="${ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL%%\#*}"
  abby_manifest_path="${abby_manifest_path%%\?*}"
  if [ "$abby_manifest_host" = "huggingface.co" ] \
    && ! printf '%s' "$abby_manifest_path" \
      | LC_ALL=C grep -Eq '/resolve/[0-9a-fA-F]{40,64}/'; then
    echo "ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL must pin a 40-64 character Hugging Face commit SHA" >&2
    exit 1
  fi
fi

abby_runtime_config_template_path="${ABBY_RUNTIME_CONFIG_TEMPLATE_PATH:-/opt/abby/runtime-config.template.json}"
abby_runtime_config_output_path="${ABBY_RUNTIME_CONFIG_OUTPUT_PATH:-/usr/share/nginx/html/runtime-config.json}"

envsubst \
  '${ABBY_RUNTIME_WALLET_API_BASE_URL} ${ABBY_RUNTIME_WALLET_ID} ${ABBY_RUNTIME_ACTOR_DID} ${ABBY_RUNTIME_ISSUER_KEY_HEX} ${ABBY_RUNTIME_AUDIENCE_KEY_HEX} ${ABBY_RUNTIME_FILECOIN_UPLOAD_URL} ${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN} ${ABBY_RUNTIME_VOICE_PROXY_ENABLED} ${ABBY_RUNTIME_VOICE_PROXY_MODEL} ${ABBY_RUNTIME_VOICE_PROXY_BASE_URL} ${ABBY_RUNTIME_VOICE_PROXY_INFER_URL} ${ABBY_RUNTIME_VOICE_PROXY_TTS_URL} ${ABBY_RUNTIME_VOICE_PROXY_STT_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_INFER_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_TTS_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_STT_URL} ${ABBY_RUNTIME_VOICE_PROXY_FALLBACK_MODEL} ${ABBY_RUNTIME_PRECOMPUTED_AUDIO_MANIFEST_URL} ${ABBY_RUNTIME_GRAPH_RAG_PRERENDER_MATCH_THRESHOLD}' \
  < "$abby_runtime_config_template_path" \
  > "$abby_runtime_config_output_path"
