#!/bin/sh
set -eu

export ABBY_RUNTIME_WALLET_API_BASE_URL="${ABBY_RUNTIME_WALLET_API_BASE_URL:-${VITE_WALLET_API_BASE_URL:-same-origin}}"
export ABBY_RUNTIME_WALLET_ID="${ABBY_RUNTIME_WALLET_ID:-}"
export ABBY_RUNTIME_ACTOR_DID="${ABBY_RUNTIME_ACTOR_DID:-}"
export ABBY_RUNTIME_ISSUER_KEY_HEX="${ABBY_RUNTIME_ISSUER_KEY_HEX:-}"
export ABBY_RUNTIME_AUDIENCE_KEY_HEX="${ABBY_RUNTIME_AUDIENCE_KEY_HEX:-}"
export ABBY_RUNTIME_FILECOIN_UPLOAD_URL="${ABBY_RUNTIME_FILECOIN_UPLOAD_URL:-}"
export ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN="${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN:-}"

envsubst \
  '${ABBY_RUNTIME_WALLET_API_BASE_URL} ${ABBY_RUNTIME_WALLET_ID} ${ABBY_RUNTIME_ACTOR_DID} ${ABBY_RUNTIME_ISSUER_KEY_HEX} ${ABBY_RUNTIME_AUDIENCE_KEY_HEX} ${ABBY_RUNTIME_FILECOIN_UPLOAD_URL} ${ABBY_RUNTIME_FILECOIN_CLIENT_TOKEN}' \
  < /opt/abby/runtime-config.template.json \
  > /usr/share/nginx/html/runtime-config.json